### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by cirrusUK** [magsol/pybot#5]
hi, i git cloned this, this what i get, idk if i doin somin wrong or somin is amiss with the script, cheers 
cirrus@blade  pybot  python pybot.py create -n ibot  
  File "pybot.py", line 69
    print 'Command "%s" not recognized.' % args['sub_name']
                                       ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by magsol** [comment]
I issued the same command and it worked fine. Are you running Python 3.x? In that case, the `print()` command is a full function instead of a pseudo-construct in 2.x, which is what this code is written in.

**Comment by cirrusUK** [comment]
thanks magsol, yes i use arch so python 3, ty for the pointers
