### ISSUE TITLE
[Features] set limits

### ISSUE THREAD

**Issue by zodman** [magsol/pybot#9]
Im using your code for more than a two weeks and it works ....

the bot needs a limit time of actions on period of time like:

example:
        self.fav_limit = 3
        self._fav_limit =0
        self.config["%s_interval" % "search" ] = 60*5
       #limit the fav each 5 min.

**Comment by magsol** [comment]
Sorry, I'm not sure I follow; you want a limit to the number of times a particular action can happen within a span of time, e.g. no more than 1 favorite every 5 minutes?

**Comment by zodman** [comment]
yeap! for example on a search i can send a reply ... after 5 replies the api block me forever ...

**Comment by magsol** [comment]
When you implement an action handler, why not simply set the sleep time to be however long you want between those actions?

For example, if you're trying to search for something to favorite, put a 5-minute sleep time between calls to `on_search` and make sure it only favorites 1 thing each time it's called.

**Comment by magsol** [comment]
Closing for now, as this seems to be a feature request that is already implemented. Feel free to reopen if this is not the case.
